### ISSUE TITLE
Issue with single entry edit

### ISSUE THREAD

**Issue by wslee00** [pozil/sfdc-ui-lookup#1] opened 2018-06-26 20:35 UTC
Hi,
There is an issue with the single entry edit where the icon was covering the chosen selection.

I think I've found the issue by adding the "slds-combobox__input-value" class to line 48 in the Lookup component.  Not sure how to create pull-requests on here, so just posting this as an issue.

**Comment by pozil** [comment] 2018-06-27 07:12
Thanks for catching that and suggesting a fix @wslee00.
I have added the class you suggested and the issue is resolved in the latest versions.

**Closed as completed by pozil** 2018-06-27 07:12 UTC

**Comment by wslee00** [comment] 2018-06-27 12:44
One other thing that I've added to the class is an onchange event, as I
wanted to take an action whenever the user changed the value of the input
field.  Any chance you would want that included as well?

**Comment by pozil** [comment] 2018-06-28 08:39
Ok, I'll think about it.

In the meantime, you can achieve this by just adding a [change handler](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_cb_data_change.htm) on the value in the parent component.
